import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./_layouts/Header";
import Sidebar from "./_layouts/Sidebar";
import Head from "./_layouts/Head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <Head />
      <body className={inter.className}>
        <Header />
        <div className="flex flex-row">
          <div className="basis-1/5">
            <Sidebar />
          </div>
          <div className="basis-4/5">{children}</div>
        </div>
      </body>
    </html>
  );
}
